name: Notify Discord of New Release

on:
  release:
    types: [published]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord
        env:
          # The secret containing the Discord webhook URL
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        # Use the recommended pinned version for stability:
        uses: Ilshidur/action-discord@0.3.2
        with:
          # Customize your message. Event payload variables are available:
          args: |
            **{{ EVENT_PAYLOAD.repository.name }}** just published a new release! 
            Tag: **{{ EVENT_PAYLOAD.release.tag_name }}**  
            Link: {{ EVENT_PAYLOAD.release.html_url }}
